call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-plug'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'christoomey/vim-system-copy'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'scrooloose/syntastic'
Plug 'airblade/vim-gitgutter'
Plug 'easymotion/vim-easymotion'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'ervandew/supertab'
Plug 'flazz/vim-colorschemes'
Plug 'terryma/vim-multiple-cursors'
Plug 'yggdroot/indentline'
Plug 'reewr/vim-monokai-phoenix'
Plug 'bronson/vim-trailing-whitespace'
Plug 'mbbill/undotree'
Plug 'tpope/vim-surround'
Plug 'townk/vim-autoclose'
Plug 'shougo/neocomplete.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'xuyuanp/nerdtree-git-plugin'
Plug 'gregsexton/gitv'
Plug 'lervag/vimtex'
Plug 'dhruvasagar/vim-table-mode'
Plug 'chazy/cscope_maps'
Plug 'maxbrunsfeld/vim-yankstack'
Plug 'majutsushi/tagbar'
Plug 'sjl/gundo.vim'
Plug 'shougo/neossh.vim'
Plug 'rust-lang/rust.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'jakykong/vim-zim'
Plug 'joanrivera/vim-zimwiki-syntax'
Plug 'vimwiki/vimwiki'
Plug 'jsfaint/gen_tags.vim'
Plug 'universal-ctags/ctags'
Plug 'romainl/vim-cool'
Plug 'vivien/vim-linux-coding-style'
call plug#end()

"Plug 'ludovicchabant/vim-gutentags'
"Plug 'skywind3000/gutentags_plus'
"Plug 'jsfaint/gen_tags.vim'
"Plug 'jcliang/vim-cscope-utils'
"Plug 'brookhong/cscope.vim'
"Plug 'vim-scripts/autoload_cscope.vim'

" vim-cool
let g:CoolTotalMatches = 1

syntax enable       	" enable syntax processing
"set number              " show line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set foldenable          " enable folding
set foldlevelstart=20
set colorcolumn=81
"set textwidth=80
set mouse=a
set tabstop=8
set shiftwidth=4
set softtabstop=8
set expandtab
set autoindent
set smartindent
set smarttab
set copyindent
set preserveindent
set smartcase
set ignorecase

"freebsd/linux code
"set noexpandtab
"set shiftwidth=8
let g:linuxsty_patterns = [ "/usr/src/", "/linux", "/fedora-linux" ]
autocmd BufNewFile,BufRead /home/stefano/repos/linux* call SetLinuxOptions()
autocmd BufNewFile,BufRead /home/stefano/repos/fedora-linux* call SetLinuxOptions()
function SetLinuxOptions()
    set list lcs=tab:\|\ 
    hi SpecialKey ctermfg=DarkGrey ctermbg=None
endfunction

set backspace=indent,eol,start

let g:gitgutter_enabled = 1

" Shit+Tab to insert Tab
inoremap <S-Tab> <C-V><Tab>

filetype plugin indent on
set nocompatible
filetype plugin on

highlight clear SignColumn

let mapleader = ","

filetype plugin on
filetype plugin indent on
colorscheme SlateDark

set laststatus=2	" show the status bar
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='cool'

let g:neocomplete#enable_at_startup = 1

if has("persistent_undo")
    set undodir=~/.undodir/
    set undofile
endif

" split navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" auto going to last line
if has("autocmd")
  autocmd BufReadPost *
  \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
  \ |   exe "normal! g`\""
  \ | endif
endif

" nerdtree
map <leader>nn :NERDTreeToggle<CR>

"yankstack
nmap <leader>p <Plug>yankstack_substitute_older_paste
nmap <leader>P <Plug>yankstack_substitute_newer_paste

" buffer exploration
nnoremap <C-b> :bnext<CR>

" ctags support
set tags+=./tags;/,tags;/
set tags+=/var/tmp/tags

nnoremap <F5> :GundoToggle<CR>
nmap <F8> :TagbarToggle<CR>

" syntestic
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0

" YouCompleteMe parameters
"let g:ycm_confirm_extra_conf = 0
"nnoremap <leader>yd :YcmCompleter GetDoc<CR>
"nnoremap <leader>yt :YcmCompleter GetType<CR>
"nnoremap <leader>yg :YcmCompleter GoTo<CR>
"let g:ycm_autoclose_preview_window_after_completion = 1
"let g:ycm_global_ycm_extra_conf = "/home/stefano/.vim_runtime/sources_non_forked/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py"
" disable error report
"let g:ycm_enable_diagnostic_signs = 0
"let g:ycm_enable_diagnostic_highlighting = 0


" Rust
function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gs <plug>(lsp-document-symbol-search)
    nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gi <plug>(lsp-implementation)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)
    nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
    nnoremap <buffer> <expr><c-d> lsp#scroll(-4)

    nmap gx :LspStopServer<CR>

    let g:lsp_format_sync_timeout = 1000
    autocmd! BufWritePre *.rs,*.go call execute('LspDocumentFormatSync')

    " refer to doc to add more commands
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

let g:tex_flavor = 'latex'

" fix issue with middle mouse and kitty
nnoremap <MiddleMouse> <Nop>
nnoremap <2-MiddleMouse> <Nop>
nnoremap <3-MiddleMouse> <Nop>
nnoremap <4-MiddleMouse> <Nop>

inoremap <MiddleMouse> <Nop>
inoremap <2-MiddleMouse> <Nop>
inoremap <3-MiddleMouse> <Nop>
inoremap <4-MiddleMouse> <Nop>
