# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
#ZSH_THEME="robbyrussell"
#ZSH_THEME="agnoster"
#ZSH_THEME="tjkirch"
ZSH_THEME="stefano"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  autojump git gitfast git-extras wd svn dircycle colorize colored-man-pages sudo cp web-search sublime history history-substring-search docker rust cargo ansible emoji copyfile colorize gitignore golang pip vscode
)
#plugins=($plugins kubectl minikube)
plugins=($plugins minikube)

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

export TERM="xterm-256color"


# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

if [[ "$OSTYPE" == linux* || "$OSTYPE" == freebsd* ]]; then
    eval `keychain --eval id_rsa`

    {
	    source /etc/os-release
	    if [[ "$ID" == fedora ]]; then
		    plugins=($plugins dnf)
	    elif [[ "$ID" == arch* ]]; then
		    plugins=($plugins archlinux)
	    fi
    }

    # My app
    export PATH="$HOME/bin:$PATH"

    # PIP
    export PATH="$HOME/.local/bin:$PATH"

    # Rust
    export PATH="$HOME/.cargo/bin:$PATH"
    export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"

    if [[ "$HOST" == "stefano-l450" ]]; then
        # lauterbach
        export T32SYS=/opt/t32
        export T32TMP=/tmp
        export T32ID=T32
        export ADOBE_PATH=/opt/Adobe/Reader9
        export PATH=$PATH:/opt/t32/bin/pc_linux64
    fi
elif [[ "$OSTYPE" == darwin* ]]; then
    export PATH="$PATH:/usr/local/texlive/2014/bin/x86_64-darwin"
    export PATH="/usr/local/opt/python/libexec/bin:$PATH"
    LC_CTYPE=en_US.UTF-8
    LC_ALL=en_US.UTF-8
    plugins=($plugins osx brew brew-cask)
fi

source $ZSH/oh-my-zsh.sh
